### ISSUE TITLE
Skrypt przestał działać

### ISSUE THREAD

**Issue by GoogleCodeExporter** [zembrowski/phpsms-pl#1]
```
Wygląda na to, że Orange zmieniło coś na swojej stronie i skrypt przestał 
działać.

```

Original issue reported on code.google.com by `pite...@tlen.pl` on 19 Apr 2015 at 10:59

**Comment by zembrowski** [comment]
Issue solved with https://github.com/zembrowski/phpsms-pl/issues/3
