### ISSUE TITLE
Nie działa

### ISSUE THREAD

**Issue by GoogleCodeExporter** [zembrowski/phpsms-pl#2]
```
Niestety orange zmieniło sposób logowania.

Niestety sam nie umiem poprawić. Może autor pomoże :)pzdr

```

Original issue reported on code.google.com by `7g...@wp.pl` on 19 May 2015 at 2:53

**Comment by zembrowski** [comment]
Issue solved with https://github.com/zembrowski/phpsms-pl/issues/3
