### ISSUE TITLE
Patch for /trunk/sms.orange.php

### ISSUE THREAD

**Issue by GoogleCodeExporter** [zembrowski/phpsms-pl#3]
```
Poprawka do funkcji login po ostatniej modyfikacji strony Orange.
```

Original issue reported on code.google.com by `pite...@tlen.pl` on 19 May 2015 at 5:55

Attachments:
* [sms.orange.php.patch](https://storage.googleapis.com/google-code-attachments/phpsms-pl/issue-3/comment-0/sms.orange.php.patch)

**Comment by zembrowski** [comment]
Solved by user "Happy Camel" on May 19th, 2015 at Google Code. Patch incorporated on 2016-02-07.

Dzięki za patch!
